
Link.create(url: 'http://www.example.com')
Link.create(url: 'http://www.example.com')
Link.create(url: 'http://www.example.com')
Link.create(url: 'http://www.example.com')

Bio.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum hendrerit nisl ac sapien vestibulum pretium. Nam rhoncus augue a venenatis cursus. Morbi maximus maximus odio sit amet laoreet. Ut sollicitudin, neque vel rutrum facilisis, justo mauris consectetur metus, sed pellentesque sapien nisi in est. Vivamus tristique tortor vulputate, sollicitudin arcu rhoncus, varius metus. Phasellus consequat ac dolor at mollis. Sed ex tellus, lacinia at augue sit amet, ultricies accumsan quam. Maecenas at ipsum augue.

Etiam ut commodo felis. In vitae enim sed tortor tincidunt commodo et ac libero. Etiam est ex, mollis nec massa quis, mattis fringilla nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus vitae nisi felis. Pellentesque urna lectus, tempus sed lacus eu, facilisis consequat tortor. Donec cursus libero tempus tincidunt bibendum. Phasellus interdum pharetra felis sed vestibulum.

Integer dignissim quis arcu eu mattis. Donec eget sollicitudin nunc. Nunc vitae nibh neque. Duis condimentum felis a facilisis placerat. Sed aliquet ultricies posuere. In dui risus, pulvinar non nibh vitae, rhoncus sollicitudin leo. Maecenas non sodales libero. Donec eleifend sapien nunc, auctor vulputate urna ullamcorper non. Ut in augue non nisi imperdiet bibendum ut in metus. Cras vitae dui ante. Donec eget risus quis justo imperdiet bibendum. Duis vel mi luctus, imperdiet ex sed, volutpat turpis. Duis eleifend nunc sit amet ante lobortis tristique. Duis molestie, nisl a iaculis aliquet, est urna feugiat dolor, id tempor lorem sem in mauris.

Donec eu ullamcorper felis, at maximus ipsum. Fusce massa quam, sagittis ac eros tempus, condimentum finibus justo. Curabitur vitae elementum dolor, vitae vehicula mi. Maecenas ultricies sem id odio maximus faucibus. Donec bibendum lectus sapien, vel pharetra ante semper in. Vestibulum in facilisis lacus. Suspendisse eget erat arcu. Nam in egestas erat. Morbi fermentum lorem eget mauris posuere, quis suscipit magna lobortis. Integer non elit efficitur, cursus lectus quis, dapibus nulla. Integer pretium molestie diam eu consequat. Nulla quis urna ac velit ornare malesuada vel eu neque.

Nulla maximus tempor ante, non lobortis risus venenatis in. Sed risus leo, ultrices a dui sagittis, feugiat aliquam lacus. Nunc rhoncus urna eget nibh ullamcorper, sed varius odio egestas. Integer molestie, tortor nec viverra luctus, elit tellus faucibus odio, nec convallis leo nisi at quam. Suspendisse interdum justo quis vestibulum aliquam. In congue vehicula leo vel vulputate. Ut maximus volutpat purus, in mattis nulla auctor in. In eu orci semper risus sollicitudin gravida. Donec id purus vitae augue bibendum tempus. Suspendisse et mollis purus, et pretium tortor. Suspendisse sed ultrices tellus. Phasellus et sagittis mi, in luctus enim.")

Post.create(title: "FIRST", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque elementum a augue vitae viverra. Phasellus fringilla felis ac condimentum blandit. Maecenas dapibus mi id sem tempor, vitae finibus diam condimentum. Nunc magna lorem, molestie in augue sed, fermentum facilisis nulla. Proin dui turpis, sollicitudin porta venenatis eu, pretium sed diam. Vestibulum eget consectetur urna. Donec laoreet pretium dui. Curabitur felis lorem, euismod sed fringilla sit amet, aliquet ut risus. Sed orci justo, laoreet nec condimentum et, dignissim vitae nunc. Maecenas a tellus semper, imperdiet purus id, dapibus ipsum. Duis pulvinar scelerisque ligula ut congue. Ut massa purus, imperdiet imperdiet convallis sit amet, posuere in libero. Phasellus porttitor, est nec ornare aliquet, ante libero semper turpis, vel ornare urna sapien quis massa.")
Post.create(title: "SECOND", body: "Fusce condimentum eleifend venenatis. Vivamus blandit, libero vitae dictum tempus, ipsum elit luctus ligula, vel lacinia nisi purus sit amet nisi. Sed a consequat enim. Maecenas arcu dolor, interdum vitae lobortis vel, viverra cursus est. Donec ultrices magna ut lacinia vulputate. Vivamus tincidunt sit amet diam et ornare. Curabitur ut tristique ante. Suspendisse ligula sem, venenatis non orci eu, porta dignissim neque. Fusce at consectetur diam. Nulla facilisi. Sed neque nulla, vehicula et odio a, accumsan ullamcorper odio. Mauris posuere rhoncus turpis, eu luctus ex elementum id. Curabitur nulla felis, tristique fringilla gravida accumsan, tincidunt non odio. Nulla eget sapien lorem. Quisque sodales, purus non aliquam venenatis, tortor diam dignissim turpis, in fermentum dolor dui ut metus.")
Post.create(title: "THIRD TITLE YO", body: "Mauris vehicula gravida erat, et lobortis neque facilisis id. Quisque nunc ex, semper a dolor vitae, pharetra varius risus. In rhoncus egestas posuere. Nunc eleifend lacinia odio, in dictum metus. Sed sed aliquet metus, ut efficitur metus. Aenean sit amet sollicitudin ligula. In lorem ligula, convallis vel cursus ut, accumsan non est. Morbi cursus mauris eu iaculis malesuada. Etiam id massa in orci ultricies malesuada sit amet vitae tellus. Duis imperdiet tempor vehicula. Nam sagittis, justo vitae tempus vestibulum, libero orci fermentum risus, a tempor orci orci id nulla. Maecenas risus nulla, faucibus nec felis et, fringilla varius mi. Suspendisse pulvinar quam non massa elementum, quis ultricies mi placerat. Nulla ac velit et nulla tincidunt vehicula sed vitae velit. Aliquam congue facilisis augue ut fringilla.")
Post.create(title: "FOURTH TITLE YAY", body: "Fusce condimentum eleifend venenatis. Vivamus blandit, libero vitae dictum tempus, ipsum elit luctus ligula, vel lacinia nisi purus sit amet nisi. Sed a consequat enim. Maecenas arcu dolor, interdum vitae lobortis vel, viverra cursus est. Donec ultrices magna ut lacinia vulputate. Vivamus tincidunt sit amet diam et ornare. Curabitur ut tristique ante. Suspendisse ligula sem, venenatis non orci eu, porta dignissim neque. Fusce at consectetur diam. Nulla facilisi. Sed neque nulla, vehicula et odio a, accumsan ullamcorper odio. Mauris posuere rhoncus turpis, eu luctus ex elementum id. Curabitur nulla felis, tristique fringilla gravida accumsan, tincidunt non odio. Nulla eget sapien lorem. Quisque sodales, purus non aliquam venenatis, tortor diam dignissim turpis, in fermentum dolor dui ut metus.")
Post.create(title: "FIFTH TITLE", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque elementum a augue vitae viverra. Phasellus fringilla felis ac condimentum blandit. Maecenas dapibus mi id sem tempor, vitae finibus diam condimentum. Nunc magna lorem, molestie in augue sed, fermentum facilisis nulla. Proin dui turpis, sollicitudin porta venenatis eu, pretium sed diam. Vestibulum eget consectetur urna. Donec laoreet pretium dui. Curabitur felis lorem, euismod sed fringilla sit amet, aliquet ut risus. Sed orci justo, laoreet nec condimentum et, dignissim vitae nunc. Maecenas a tellus semper, imperdiet purus id, dapibus ipsum. Duis pulvinar scelerisque ligula ut congue. Ut massa purus, imperdiet imperdiet convallis sit amet, posuere in libero. Phasellus porttitor, est nec ornare aliquet, ante libero semper turpis, vel ornare urna sapien quis massa.")
Post.create(title: "SIXTH TITLE", body: "Fusce condimentum eleifend venenatis. Vivamus blandit, libero vitae dictum tempus, ipsum elit luctus ligula, vel lacinia nisi purus sit amet nisi. Sed a consequat enim. Maecenas arcu dolor, interdum vitae lobortis vel, viverra cursus est. Donec ultrices magna ut lacinia vulputate. Vivamus tincidunt sit amet diam et ornare. Curabitur ut tristique ante. Suspendisse ligula sem, venenatis non orci eu, porta dignissim neque. Fusce at consectetur diam. Nulla facilisi. Sed neque nulla, vehicula et odio a, accumsan ullamcorper odio. Mauris posuere rhoncus turpis, eu luctus ex elementum id. Curabitur nulla felis, tristique fringilla gravida accumsan, tincidunt non odio. Nulla eget sapien lorem. Quisque sodales, purus non aliquam venenatis, tortor diam dignissim turpis, in fermentum dolor dui ut metus.")
Post.create(title: "SEVENTH TITLE", body: "Mauris vehicula gravida erat, et lobortis neque facilisis id. Quisque nunc ex, semper a dolor vitae, pharetra varius risus. In rhoncus egestas posuere. Nunc eleifend lacinia odio, in dictum metus. Sed sed aliquet metus, ut efficitur metus. Aenean sit amet sollicitudin ligula. In lorem ligula, convallis vel cursus ut, accumsan non est. Morbi cursus mauris eu iaculis malesuada. Etiam id massa in orci ultricies malesuada sit amet vitae tellus. Duis imperdiet tempor vehicula. Nam sagittis, justo vitae tempus vestibulum, libero orci fermentum risus, a tempor orci orci id nulla. Maecenas risus nulla, faucibus nec felis et, fringilla varius mi. Suspendisse pulvinar quam non massa elementum, quis ultricies mi placerat. Nulla ac velit et nulla tincidunt vehicula sed vitae velit. Aliquam congue facilisis augue ut fringilla.")
Post.create(title: "EIGHTH TITLE", body: "Fusce condimentum eleifend venenatis. Vivamus blandit, libero vitae dictum tempus, ipsum elit luctus ligula, vel lacinia nisi purus sit amet nisi. Sed a consequat enim. Maecenas arcu dolor, interdum vitae lobortis vel, viverra cursus est. Donec ultrices magna ut lacinia vulputate. Vivamus tincidunt sit amet diam et ornare. Curabitur ut tristique ante. Suspendisse ligula sem, venenatis non orci eu, porta dignissim neque. Fusce at consectetur diam. Nulla facilisi. Sed neque nulla, vehicula et odio a, accumsan ullamcorper odio. Mauris posuere rhoncus turpis, eu luctus ex elementum id. Curabitur nulla felis, tristique fringilla gravida accumsan, tincidunt non odio. Nulla eget sapien lorem. Quisque sodales, purus non aliquam venenatis, tortor diam dignissim turpis, in fermentum dolor dui ut metus.")
Post.create(title: "NINTH TITLE", body: "Mauris vehicula gravida erat, et lobortis neque facilisis id. Quisque nunc ex, semper a dolor vitae, pharetra varius risus. In rhoncus egestas posuere. Nunc eleifend lacinia odio, in dictum metus. Sed sed aliquet metus, ut efficitur metus. Aenean sit amet sollicitudin ligula. In lorem ligula, convallis vel cursus ut, accumsan non est. Morbi cursus mauris eu iaculis malesuada. Etiam id massa in orci ultricies malesuada sit amet vitae tellus. Duis imperdiet tempor vehicula. Nam sagittis, justo vitae tempus vestibulum, libero orci fermentum risus, a tempor orci orci id nulla. Maecenas risus nulla, faucibus nec felis et, fringilla varius mi. Suspendisse pulvinar quam non massa elementum, quis ultricies mi placerat. Nulla ac velit et nulla tincidunt vehicula sed vitae velit. Aliquam congue facilisis augue ut fringilla.")
Post.create(title: "TENTH MOST RECENT", body: "Fusce condimentum eleifend venenatis. Vivamus blandit, libero vitae dictum tempus, ipsum elit luctus ligula, vel lacinia nisi purus sit amet nisi. Sed a consequat enim. Maecenas arcu dolor, interdum vitae lobortis vel, viverra cursus est. Donec ultrices magna ut lacinia vulputate. Vivamus tincidunt sit amet diam et ornare. Curabitur ut tristique ante. Suspendisse ligula sem, venenatis non orci eu, porta dignissim neque. Fusce at consectetur diam. Nulla facilisi. Sed neque nulla, vehicula et odio a, accumsan ullamcorper odio. Mauris posuere rhoncus turpis, eu luctus ex elementum id. Curabitur nulla felis, tristique fringilla gravida accumsan, tincidunt non odio. Nulla eget sapien lorem. Quisque sodales, purus non aliquam venenatis, tortor diam dignissim turpis, in fermentum dolor dui ut metus.")

Video.create!(title: "Cute Corgi", body: "In tincidctus. Phasellus ias pharetra consectetur ante, in porta ipsum pretium nec. Nulla at arcu convallis, posuere velit vel, venenatis eros. Ut vel dolor tellus. Phasellus porttitor justo elit. Mauris venenatis vitae sapien vel mattis. Phasellus congue ligula at lobortis blandit. Mauris porta sodales urna eget maximus.", link: "GqUY4Jqacu0" )
Video.create!(title: "More Cute Corgis", body: "In tincidunt, arcu vitae vulputate elementum, eros justo bibendum diam, at tristique quam elit sed justo. Cras rhoncus nisl at quam gravida molestie. Mauris tincidunt nisi sit amet elit iaculis luctus. Phasellus id euismod orci. Curabitur quis lacus erat. Maecenas pharetra consectetur ante, in porta ipsum pretium nec. Nulla at arcu convallis, posuere velit vel, venenatis eros. Ut vel dolor tellus. Phasellus porttitor justo elit. Mauris venenatis vitae sapien vel mattis. Phasellus congue ligula at lobortis blandit. Mauris porta sodales urna eget maximus.", link: "jx4u4ayofDA")
Video.create!(title: "Shopping With Goro", body: "In auctor ultrices odio vitae vestibulum. Duis aliquet nibh nec arcu rutrum rutrum. Curabitur sit amet elementum elit, at suscipit ante. Etiam vehicula venenatis orci non scelerisque. Nam vitae malesuada augue, sit amet iaculis metus. Ut aliquam, lacus ac sagittis feugiat, neque ligula vestibulum enim, ac faucibus turpis massa ut quam. Praesent sagittis dictum ultricies. Cras eu faucibus ante. Quisque ut arcu convallis, sodales mi nec, rhoncus nisi. Morbi feugiat nulla lorem, in placerat nibh suscipit eu. Praesent nec felis vitae felis venenatis tincidunt venenatis id sapien. Curabitur ac mi eros. Sed ac pharetra est. Mauris sollicitudin euismod sapien, non feugiat elit rhoncus pulvinar.", link: "JDv4gWutFsM")
Video.create!(title: "Cute Corgi", body: "In tincidctus. Phasellus ias pharetra consectetur ante, in porta ipsum pretium nec. Nulla at arcu convallis, posuere velit vel, venenatis eros. Ut vel dolor tellus. Phasellus porttitor justo elit. Mauris venenatis vitae sapien vel mattis. Phasellus congue ligula at lobortis blandit. Mauris porta sodales urna eget maximus.", link: "GqUY4Jqacu0" )
Video.create!(title: "More Cute Corgis", body: "In tincidunt, arcu vitae vulputate elementum, eros justo bibendum diam, at tristique quam elit sed justo. Cras rhoncus nisl at quam gravida molestie. Mauris tincidunt nisi sit amet elit iaculis luctus. Phasellus id euismod orci. Curabitur quis lacus erat. Maecenas pharetra consectetur ante, in porta ipsum pretium nec. Nulla at arcu convallis, posuere velit vel, venenatis eros. Ut vel dolor tellus. Phasellus porttitor justo elit. Mauris venenatis vitae sapien vel mattis. Phasellus congue ligula at lobortis blandit. Mauris porta sodales urna eget maximus.", link: "jx4u4ayofDA")
Video.create!(title: "Shopping With Goro", body: "In auctor ultrices odio vitae vestibulum. Duis aliquet nibh nec arcu rutrum rutrum. Curabitur sit amet elementum elit, at suscipit ante. Etiam vehicula venenatis orci non scelerisque. Nam vitae malesuada augue, sit amet iaculis metus. Ut aliquam, lacus ac sagittis feugiat, neque ligula vestibulum enim, ac faucibus turpis massa ut quam. Praesent sagittis dictum ultricies. Cras eu faucibus ante. Quisque ut arcu convallis, sodales mi nec, rhoncus nisi. Morbi feugiat nulla lorem, in placerat nibh suscipit eu. Praesent nec felis vitae felis venenatis tincidunt venenatis id sapien. Curabitur ac mi eros. Sed ac pharetra est. Mauris sollicitudin euismod sapien, non feugiat elit rhoncus pulvinar.", link: "JDv4gWutFsM")
Video.create!(title: "Cute Corgi", body: "In tincidctus. Phasellus ias pharetra consectetur ante, in porta ipsum pretium nec. Nulla at arcu convallis, posuere velit vel, venenatis eros. Ut vel dolor tellus. Phasellus porttitor justo elit. Mauris venenatis vitae sapien vel mattis. Phasellus congue ligula at lobortis blandit. Mauris porta sodales urna eget maximus.", link: "GqUY4Jqacu0" )
Video.create!(title: "More Cute Corgis", body: "In tincidunt, arcu vitae vulputate elementum, eros justo bibendum diam, at tristique quam elit sed justo. Cras rhoncus nisl at quam gravida molestie. Mauris tincidunt nisi sit amet elit iaculis luctus. Phasellus id euismod orci. Curabitur quis lacus erat. Maecenas pharetra consectetur ante, in porta ipsum pretium nec. Nulla at arcu convallis, posuere velit vel, venenatis eros. Ut vel dolor tellus. Phasellus porttitor justo elit. Mauris venenatis vitae sapien vel mattis. Phasellus congue ligula at lobortis blandit. Mauris porta sodales urna eget maximus.", link: "jx4u4ayofDA")
Video.create!(title: "Shopping With Goro", body: "In auctor ultrices odio vitae vestibulum. Duis aliquet nibh nec arcu rutrum rutrum. Curabitur sit amet elementum elit, at suscipit ante. Etiam vehicula venenatis orci non scelerisque. Nam vitae malesuada augue, sit amet iaculis metus. Ut aliquam, lacus ac sagittis feugiat, neque ligula vestibulum enim, ac faucibus turpis massa ut quam. Praesent sagittis dictum ultricies. Cras eu faucibus ante. Quisque ut arcu convallis, sodales mi nec, rhoncus nisi. Morbi feugiat nulla lorem, in placerat nibh suscipit eu. Praesent nec felis vitae felis venenatis tincidunt venenatis id sapien. Curabitur ac mi eros. Sed ac pharetra est. Mauris sollicitudin euismod sapien, non feugiat elit rhoncus pulvinar.", link: "JDv4gWutFsM")

Show.create(what: "AMAN", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "AMAN", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "DMG", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "DMG", where: "EXAMPLE OF PLACE WITH LONG NAME - LONDON", when: DateTime.now, how: "www.google.com")
Show.create(what: "DMG", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "AMAN", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "AMAN", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "AMAN", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "DMG", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "DMG", where: "EXAMPLE OF PLACE WITH LONG NAME - LONDON", when: DateTime.now, how: "www.google.com")
Show.create(what: "DMG", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "AMAN", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "AMAN", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "AMAN", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "DMG", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "DMG", where: "EXAMPLE OF PLACE WITH LONG NAME - LONDON", when: DateTime.now, how: "www.google.com")
Show.create(what: "DMG", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")
Show.create(what: "AMAN", where: "ROOFTOP - NEW YORK", when: DateTime.now, how: "www.google.com")

Tool.create(link: 'google.com', text: 'IBANEZ')
Tool.create(link: 'google.com', text: 'MORLEY')
Tool.create(link: 'google.com', text: 'THIRD TOOL')
Tool.create(link: 'google.com', text: 'BANDCAMP')

Gallery.create(name: 'Live')
Gallery.create(name: 'Studio')
Gallery.create(name: 'Life')
Gallery.create(name: 'On The Road')

Project.create(name: "NEW PROJECT", url: "google.com")
Project.create(name: "SECOND PROJECT", url: "google.com")
Project.create(name: "SPACEX", url: "google.com")
Project.create(name: "CORGI LOVER", url: "google.com")
Project.create(name: "CORGATHON", url: "google.com")